Add ubuntu, ssl and auth support

diff --git a/templates/user_data.j2 b/templates/user_data.j2
--- a/templates/user_data.j2
+++ b/templates/user_data.j2
@@ -1,36 +1,22 @@
 #!/bin/bash
 
+if [ ! -f /etc/os-release ]; then
+    echo "/etc/os-release is required to determine the target OS"
+    exit 1
+fi
+
+. /etc/os-release
+
 hostname {{ vm.name }}
-setenforce 0
 
-{% if branch == "dev" %}
-cat > /etc/yum.repos.d/inmanta_oss_dev.repo <<EOF
-[inmanta-oss-dev]
-name=Inmanta OSS Dev snapshots
-baseurl=https://pkg.inmanta.com/inmanta-oss-dev/el7/
-gpgcheck=1
-gpgkey=https://pkg.inmanta.com/inmanta-oss-dev/inmanta-oss-dev-public-key
-repo_gpgcheck=1
-enabled=1
-enabled_metadata=1
+function create_config() {
+    {% if ssl_ca %}
+    cat > /etc/inmanta/server.crt <<EOF
+{{ssl_ca}}
 EOF
-{% else %}
-cat > /etc/yum.repos.d/inmanta_oss_stable.repo <<EOF
-[inmanta-oss-stable]
-name=Inmanta OSS stable
-baseurl=https://pkg.inmanta.com/inmanta-oss-stable/el7/
-gpgcheck=1
-gpgkey=https://pkg.inmanta.com/inmanta-oss-stable/inmanta-oss-stable-public-key
-repo_gpgcheck=1
-enabled=1
-enabled_metadata=1
-EOF
-{% endif %}
+    {% endif %}
 
-yum install -y epel-release
-yum install -y python34-devel gcc git python3-inmanta-agent
-
-cat > /etc/inmanta/agent.cfg <<EOF
+    cat > /etc/inmanta/agent.cfg <<EOF
 [config]
 agent_splay=10
 heartbeat-interval = 60
@@ -43,7 +29,99 @@ agent-names=\$node-name
 [agent_rest_transport]
 port={{port}}
 host={{env_server}}
+{% if token -%}
+token={{token}}
+{% endif %}
+{% if ssl_ca -%}
+ssl=True
+ssl_ca_cert_file=/etc/inmanta/server.crt
+{% endif %}
+EOF
+}
+
+function install_el7() {
+    hostnamectl set-hostname {{ vm.name }}
+    setenforce 0
+
+    # Install inmanta release {{release}}
+    {% if release == "dev" %}
+    cat > /etc/yum.repos.d/inmanta_oss_dev.repo <<EOF
+[inmanta-oss-dev]
+name=Inmanta OSS Dev snapshots
+baseurl=https://pkg.inmanta.com/inmanta-oss-dev/el7/
+gpgcheck=1
+gpgkey=https://pkg.inmanta.com/inmanta-oss-dev/inmanta-oss-dev-public-key
+repo_gpgcheck=1
+enabled=1
+enabled_metadata=1
+EOF
+    {% else %}
+    cat > /etc/yum.repos.d/inmanta_oss_stable.repo <<EOF
+[inmanta-oss-stable]
+name=Inmanta OSS stable
+baseurl=https://pkg.inmanta.com/inmanta-oss-stable/el7/
+gpgcheck=1
+gpgkey=https://pkg.inmanta.com/inmanta-oss-stable/inmanta-oss-stable-public-key
+repo_gpgcheck=1
+enabled=1
+enabled_metadata=1
+EOF
+    {% endif %}
+
+    yum install -y epel-release
+    yum install -y python34-devel gcc git python3-inmanta-agent
+
+    create_config
+
+    systemctl start inmanta-agent
+    systemctl enable inmanta-agent
+}
+
+function install_ubuntu() {
+    hostname {{ vm.name }}
+    echo {{ vm.name }} > /etc/hostname
+
+    apt-get update
+    apt-get install -y python3 python3-pip git python-virtualenv libffi-dev
+
+    virtualenv -p python3 /opt/inmanta
+
+    /opt/inmanta/bin/pip3 install -U pip
+    /opt/inmanta/bin/pip3 install -U setuptools
+    # Install inmanta release {{release}}
+    {% if release == "master" -%}
+    /opt/inmanta/bin/pip3 install git+https://github.com/inmanta/inmanta#egg=inmanta
+    {% else -%}
+    /opt/inmanta/bin/pip3 install inmanta
+    {% endif %}
+
+    mkdir -p /etc/inmanta
+    create_config
+
+    cat > /etc/init/inmanta.conf <<EOF
+# inmanta - Inmanta cfg mgmt agent
+#
+# Inmanta agent
+description "Inmanta"
+
+start on runlevel [2345]
+stop on runlevel [!2345]
+
+respawn
+
+exec /opt/inmanta/bin/inmanta -c /etc/inmanta/agent.cfg -vvv agent
 EOF
 
-systemctl start inmanta-agent
-systemctl enable inmanta-agent
+    initctl reload-configuration
+    start inmanta
+}
+
+if [[ "$ID" == "centos" && "$VERSION_ID" == "7" ]];
+then
+    install_el7
+elif [[ "$ID" == "ubuntu" ]];
+then
+    install_ubuntu
+else
+    echo "$ID $VERSION_ID not supported"
+fi
